---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  AllowedScriptType:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: true
  RightTrim:
    enabled: true
  SelfClosingTag:
    enabled: true
